-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE USUARIO (
USUARIO BIGINT PRIMARY KEY,
SENHA VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
FOTO VARCHAR(30) NOT NULL,
LOGIN VARCHAR(20) NOT NULL
);



CREATE TABLE CATEGORIA (
CATEGORIA BIGINT PRIMARY KEY,
NOME VARCHAR(30) NOT NULL
);

CREATE TABLE SERIE (
SERIE BIGINT PRIMARY KEY,
TEMPORADA CHAR(2) NOT NULL,
NOME VARCHAR(50) NOT NULL,
TEMPO VARCHAR(3) NOT NULL,
DESCRICAO VARCHAR(1000) NOT NULL,
NOTA CHAR(1) NOT NULL,
YOUTUBE VARCHAR(50) NOT NULL,
EPISODIO CHAR(2) NOT NULL,
IMDB VARCHAR(30) NOT NULL,
CATEGORIA BIGINT NOT NULL,
FOREIGN KEY(CATEGORIA) REFERENCES CATEGORIA (CATEGORIA)
);

CREATE TABLE FILME (
FILME BIGINT PRIMARY KEY,
DESCRICAO VARCHAR(1000) NOT NULL,
NOTA CHAR(1) NOT NULL,
TEMPO VARCHAR(3) NOT NULL,
YOUTUBE VARCHAR(50) NOT NULL,
NOME VARCHAR(50) NOT NULL,
IMDB VARCHAR(30) NOT NULL,
CATEGORIA BIGINT NOT NULL,
FOREIGN KEY(CATEGORIA) REFERENCES CATEGORIA (CATEGORIA)
);

CREATE TABLE ASSISTIS (
SERIE BIGINT NOT NULL,
USUARIO BIGINT NOT NULL,
FOREIGN KEY(USUARIO) REFERENCES USUARIO (USUARIO)
);

CREATE TABLE ASSISTIF (
FILME BIGINT NOT NULL,
USUARIO BIGINT NOT NULL,
FOREIGN KEY(USUARIO) REFERENCES USUARIO (USUARIO)
);
ALTER TABLE ASSISTIS ADD FOREIGN KEY(SERIE) REFERENCES SERIE (SERIE)
ALTER TABLE ASSISTIF ADD FOREIGN KEY(FILME) REFERENCES FILME (FILME)
